https://borab96.github.io/IsingPriceDynamics/ising.html

# Setup
title:            Ising price dynamics
tagline:          null
description:      'Semi-pedagocial exploration of the use of the Ising model and its generalizations to model price '
url:              null
baseurl:          https://borab96.github.io/IsingPriceDynamics/ising.html

author:
  name:           'Bora Basa'
  url:            null